[TOC]

### 问题描述

最近在研究Django3.2和Celery5的整合，在基础配置设置完毕后，正常启动celery，然后写了如下的异步任务
```Python
def get_access_record_data(request):
    """获取访问记录需要的数据
    celery发送消息给broker时，会对任务函数及其参数进行序列化，为了避免出现额外异常情况，
    将access_record函数的参数修改为字典类型

    Args:
        request(HttpRequest): 请求体

    Returns:
        result(dict): 数据集
    """
    address = request.META.get('REMOTE_ADDR', 'unknown')
    ip_info = get_ip_info(address)
    region = [ip_info.get("country", ""), ip_info.get("regionName", ""), ip_info.get("city", "")]

    data = {
        "path": request.META.get('PATH_INFO', ''),
        'query_str': request.META.get('QUERY_STRING', ''),
        'address': address,
        'user_agent': request.META.get('HTTP_USER_AGENT', 'unknown'),
        'referer': request.META.get('HTTP_REFERER', ''),
        'atime': timezone.now(),
        'source': '-'.join(region) if ip_info else '',
    }
    return data


@shared_task
def access_record(data):
    """记录网站访问记录

    Args:
        data(dict): 数据集

    Returns:
        result(str): 执行结果
    """
    AccessRecord.objects.create(**data)
    print(f'新增访问记录：{data}')
    return "访问记录添加成功"
```

我定义了一个access_record的异步任务，用于处理访问记录数据的创建，当我刷新文章页面，触发异步任务的调用时，就报了如下的错误：
```Shell
Traceback (most recent call last):
  File "d:\work\project\phoenix\venv\lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "d:\work\project\phoenix\venv\lib\site-packages\celery\fixups\django.py", line 170, in on_task_postrun
    self.close_database()
  File "d:\work\project\phoenix\venv\lib\site-packages\celery\fixups\django.py", line 175, in close_database
    return self._close_database()
  File "d:\work\project\phoenix\venv\lib\site-packages\celery\fixups\django.py", line 187, in _close_database
    conn.close_if_unusable_or_obsolete()
  File "d:\work\project\phoenix\venv\lib\site-packages\django\db\backends\base\base.py", line 524, in close_if_unusable_or_obsolete
    self.close()
  File "d:\work\project\phoenix\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "d:\work\project\phoenix\venv\lib\site-packages\django\db\backends\base\base.py", line 285, in close
    self.validate_thread_sharing()
  File "d:\work\project\phoenix\venv\lib\site-packages\django\db\backends\base\base.py", line 557, in validate_thread_sharing
    % (self.alias, self._thread_ident, _thread.get_ident())
django.db.utils.DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id
 2024280146168 and this is thread id 2024381910008.
```

从最后一段堆栈异常来看，我找到了django的源码里
```Python
    def validate_thread_sharing(self):
        """
        Validate that the connection isn't accessed by another thread than the
        one which originally created it, unless the connection was explicitly
        authorized to be shared between threads (via the `inc_thread_sharing()`
        method). Raise an exception if the validation fails.
        """
        if not (self.allow_thread_sharing or self._thread_ident == _thread.get_ident()):
            raise DatabaseError(
                "DatabaseWrapper objects created in a "
                "thread can only be used in that same thread. The object "
                "with alias '%s' was created in thread id %s and this is "
                "thread id %s."
                % (self.alias, self._thread_ident, _thread.get_ident())
            )
```

### 问题分析

从上述的源码和堆栈异常可以看出，我们异步任务的model.objects.create()触发了Django Model的线程安全，celery执行的异步任务，和我们在django中调用的异步任务，由于是不同的线程，所以在校验时失败了。

### 解决方案

既然是触发了线程安全，那么我们就可以从两个角度解决这个问题

#### 避免在异步任务中使用create

我们可以将需要插入数据库的数据放在redis的队列中，然后写个定时任务或者启用订阅模式，定时去消费这些数据，把它们写入数据库。这种方法需要启用消息队列，有一定的工作量，可酌情考虑。

#### 使用单线程

由于我本次的开发环境是在windows下，因此启用celery的时候使用了```-P eventlet```,可以将eventlet修改为solo模式
```Shell
celery -A phoenix worker -l info -P solo
```

此方法适合对并发没有要求的场景

#### 使用gevent

```Shell
celery -A phoenix worker -l info -P gevent
```

gevent是Python的协程库，通过使用协程的概念，保证create是在同一个线程中。

### 结语

celery的命令行参数有非常多可供选择的选项，具体可参考[Celery-Command-Line](https://docs.celeryproject.org/en/stable/reference/cli.html "Celery-Command-Line")